baseURL = "https://onedayoneday.xin/"
languageCode = "zh-cn"
title = "OneDay Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowToc = true

  # 关键：让首页/列表页把 guide 也当成主内容区展示
  mainSections = ["posts", "guide"]

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "指南"
  url = "/guide/"
  weight = 3
